language: shell
os: linux
dist: focal

env:
  global:
    DOCKER_BUILDKIT: "1"
    DOCKER_CLI_EXPERIMENTAL: "enabled"

jobs:
  include:
    # build library
    - language: python
      python: 3.7

      before_install:
        - pip install poetry

      install:
        - poetry install

      script:
        - poetry run flake8 jrsub tests
        - poetry run python -m unittest discover

      deploy:
        - provider: script
          script: poetry publish --username "$PYPI_USER" --password "$PYPI_PASS" --build
          on:
            tags: true

    # deploy demo
    - language: shell

      services:
        - docker
      before_install:
        - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        - sudo service docker restart
        - docker info

      before_script:
        - curl https://cli-assets.heroku.com/install.sh | sh
        - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      script:
        - docker build -t registry.heroku.com/jsub-demo/web -f demo/flask.Dockerfile demo

      deploy:
        provider: script
        script: docker push registry.heroku.com/jsub-demo/web &&
          heroku container:release web --app jsub-demo
        on:
          condition: ($TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG)
          all_branches: true